### ISSUE TITLE
とりあえず ping pong しよ

### ISSUE THREAD

**Issue by ekuinox** [weedparty/signal-discord#4]
#1 をやる上で

ackcord使ってping pong

**Comment by ekuinox** [comment]
やれ！

**Comment by ekuinox** [comment]
- ackcordつっこむ
- Discordからトークンとってくる
- `.env`的なファイルにトークンを書いて実行時に読み込むようにする

**Comment by messcat-38** [comment]
.env的なファイルを扱う方法がわからん
env.txtなら扱えるけど".env"だとscala.io.sourceがうまく動かない

**Comment by ekuinox** [comment]
`config/secret.json` 的なファイルにしてもよし

**Comment by ekuinox** [comment]
がんばれがんばれ！

**Comment by ekuinox** [comment]
https://gist.github.com/ekuinox/1ddb9e90927a6ca6c746eb6cabd11cd7#file-main-scala
